<script>
    import { slide } from 'svelte/transition';
	import Markdown from '$lib/common/markdown/Markdown.svelte';
	import BotsharpTooltip from '$lib/common/tooltip/BotsharpTooltip.svelte';
	import Select from '$lib/common/dropdowns/Select.svelte';
	import { RuleCriteriaMode } from '$lib/helpers/enums';

    const textLimit = 1024;

    const criteriaModeOptions = [
        { label: 'LLM', value: RuleCriteriaMode.Llm },
        { label: 'Python Script', value: RuleCriteriaMode.PythonScript }
    ];

    /**
     * @type {{
     *   rule: import('$agentTypes').AgentRule,
     *   ruleIndex: number,
     *   agentId?: string,
     *   collapsed?: boolean,
     *   ruleOptions?: any[],
     *   windowWidth: number,
     *   ontoggle?: (data: { ruleIdx: number, field: string, checked: boolean }) => void,
     *   onchange?: (data: { ruleIdx: number, field: string, value: string }) => void,
     *   ondelete?: (data: { ruleIdx: number, field: string }) => void,
     *   oncollapse?: (data: { ruleIdx: number, collapsed: boolean }) => void,
     *   oncompile?: (data: { ruleIdx: number, rule: import('$agentTypes').AgentRule }) => void
     * }}
     */
    let {
        rule,
        ruleIndex,
        agentId = '',
        collapsed = true,
        ruleOptions = [],
        windowWidth,
        ontoggle,
        onchange,
        ondelete,
        oncollapse,
        oncompile
    } = $props();

    // Code script can only be generated by admins, once a trigger is picked and criteria text exists.
    let canCompile = $derived(
        !!rule.trigger_name && !!rule.criteria?.criteria?.trim()
    );

    // The rule's own mode wins; otherwise the trigger option's mode applies.
    let modePlaceholder = $derived(
        rule.default_mode ? `Trigger default (${rule.default_mode})` : 'Trigger default'
    );

    // Deep link to the code scripts page, preselected on this agent.
    let codeScriptUrl = $derived(
        agentId ? `/page/agent/code-scripts?agentId=${encodeURIComponent(agentId)}` : ''
    );

    /**
     * @param {any} e
     * @param {string} field
     */
    function toggleRule(e, field) {
        ontoggle?.({
            ruleIdx: ruleIndex,
            field: field,
            checked: e.target.checked
        });
    }

    /**
     * @param {any} e
     * @param {string} field
     */
    function changeRule(e, field) {
        const values = e?.detail?.selecteds?.map((/** @type {any} */ x) => x.value) || [];
        onchange?.({
            ruleIdx: ruleIndex,
            field: field,
            value: values[0] || ''
        });
    }

    /**
     * @param {string} field
     */
    function deleteRule(field) {
        ondelete?.({
            ruleIdx: ruleIndex,
            field: field
        });
    }

    function toggleCollapse() {
        oncollapse?.({
            ruleIdx: ruleIndex,
            collapsed: !collapsed
        });
    }

    /**
     * @param {any} e
     * @param {string} field
     */
    function changeText(e, field) {
        onchange?.({
            ruleIdx: ruleIndex,
            field: field,
            value: e?.target?.value || ''
        });
    }

    /**
     * The session token lives in sessionStorage, which a new tab does not get
     * when the link drops the opener (`rel="noopener"`, which `target="_blank"`
     * also implies on its own). Opening through window.open keeps this tab as
     * the opener, so the new tab can pull the session across and skip the login
     * page. Also covers ctrl/cmd-click, which would otherwise take the default
     * opener-less path.
     * @param {any} e
     */
    function openCodeScripts(e) {
        if (!codeScriptUrl) return;

        e.preventDefault();
        window.open(codeScriptUrl, '_blank');
    }

    function compile() {
        oncompile?.({
            ruleIdx: ruleIndex,
            rule: rule
        });
    }
</script>

<div class="ari-wrapper">
    <div class="ari-row ari-row-primary">
        <div class="ari-label ari-label-strong">
            <div class="ari-cell">
                <i
                    class="bx bx-chevron-right ari-collapse-toggle"
                    class:rotated={!collapsed}
                    role="button"
                    tabindex="0"
                    onkeydown={() => {}}
                    onclick={() => toggleCollapse()}
                ></i>
            </div>
            <div class="ari-cell">
                {`Rule #${ruleIndex + 1}`}
            </div>
            <div class="ari-tooltip-wrap">
                <label class="ari-checkbox">
                    <input
                        type="checkbox"
                        class="ari-checkbox-input"
                        checked={!rule.disabled}
                        onchange={e => toggleRule(e, 'rule')}
                    />
                    <span class="ari-checkbox-box"></span>
                </label>
                {#if rule.statement}
                <div class="ari-cell">
                    <i
                        class="bx bx-info-circle ari-info-icon"
                        id={`rule-statement-${ruleIndex}`}
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        title="Rule arguments"
                    ></i>
                    <BotsharpTooltip
                        containerClasses="agent-utility-desc"
                        style={`min-width: ${Math.floor(windowWidth*0.3)}px;`}
                        target={`rule-statement-${ruleIndex}`}
                        placement="top"
                        persist
                    >
                        <Markdown
                            rawText
                            scrollable
                            containerClasses={'markdown-div'}
                            containerStyles={`max-width: ${Math.floor(windowWidth*0.3)}px;`}
                            text={rule.statement}
                        />
                    </BotsharpTooltip>
                </div>
                {/if}
            </div>
        </div>
        <div class="ari-value">
            <div class="ari-input-wrap ari-cell">
                <Select
                    tag={`rule-trigger-${ruleIndex}`}
                    containerStyles={'width: 100%;'}
                    placeholder={'Select a trigger'}
                    searchMode
                    searchPlaceholder={'Search triggers'}
                    disabled={rule.disabled}
                    selectedValues={rule.trigger_name ? [rule.trigger_name] : []}
                    options={ruleOptions.filter(o => !!o.name).map(o => ({ label: o.displayName || o.name, value: o.name }))}
                    onselect={e => changeRule(e, 'rule')}
                />
            </div>
            <div class="ari-delete ari-cell">
                <i
                    class="bx bxs-no-entry ari-delete-icon"
                    role="link"
                    tabindex="0"
                    onkeydown={() => {}}
                    onclick={() => deleteRule('rule')}
                ></i>
            </div>
        </div>
    </div>

    {#if !collapsed}
    <div class="ari-row ari-row-secondary" transition:slide={{ duration: 200 }}>
        <div class="ari-label ari-label-strong">
            <div class="ari-cell">
                {'Message'}
            </div>
        </div>
        <div class="ari-value">
            <div class="ari-input-wrap ari-cell">
                <textarea
                    class="ari-textarea"
                    rows="3"
                    maxlength={textLimit}
                    placeholder="Message sent to the agent when this rule fires..."
                    disabled={rule.disabled}
                    value={rule.message || ''}
                    oninput={e => changeText(e, 'message')}
                ></textarea>
            </div>
            <div class="ari-delete ari-cell"></div>
        </div>
    </div>

    <div class="ari-row ari-row-secondary" transition:slide={{ duration: 200 }}>
        <div class="ari-label ari-label-strong">
            <div class="ari-cell">
                {'Criteria Mode'}
            </div>
        </div>
        <div class="ari-value">
            <div class="ari-input-wrap ari-cell">
                <Select
                    tag={`rule-criteria-mode-${ruleIndex}`}
                    containerStyles={'width: 100%;'}
                    placeholder={modePlaceholder}
                    disabled={rule.disabled}
                    selectedValues={rule.criteria?.mode ? [rule.criteria.mode] : []}
                    options={criteriaModeOptions}
                    onselect={e => changeRule(e, 'criteria_mode')}
                />
            </div>
            <div class="ari-delete ari-cell"></div>
        </div>
    </div>

    <div class="ari-row ari-row-secondary" transition:slide={{ duration: 200 }}>
        <div class="ari-label ari-label-strong">
            <div class="ari-cell">
                {#if codeScriptUrl}
                    <a
                        class="ari-label-link"
                        href={codeScriptUrl}
                        target="_blank"
                        title="Open this agent's code scripts"
                        onclick={e => openCodeScripts(e)}
                        onauxclick={e => { if (e.button === 1) openCodeScripts(e); }}
                    >
                        <span>{'Criteria Text'}</span>
                        <i class="bx bx-link-external" aria-hidden="true"></i>
                    </a>
                {:else}
                    {'Criteria Text'}
                {/if}
            </div>
            {#if canCompile}
            <div class="ari-cell">
                <i
                    class="bx bx-code-alt ari-compile-icon"
                    id={`rule-compile-${ruleIndex}`}
                    role="link"
                    tabindex="0"
                    data-bs-toggle="tooltip"
                    data-bs-placement="top"
                    title="Generate code script"
                    onkeydown={() => {}}
                    onclick={() => compile()}
                ></i>
            </div>
            {/if}
        </div>
        <div class="ari-value">
            <div class="ari-input-wrap ari-cell">
                <textarea
                    class="ari-textarea"
                    rows="5"
                    maxlength={textLimit}
                    placeholder="Describe when this rule should trigger..."
                    disabled={rule.disabled}
                    value={rule.criteria?.criteria || ''}
                    oninput={e => changeText(e, 'criteria')}
                ></textarea>
            </div>
            <div class="ari-delete ari-cell"></div>
        </div>
    </div>
    {/if}
</div>


